#
# Autogenerated by Thrift Compiler (0.9.0)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#
#  options string: py
#

from thrift.Thrift import TType, TMessageType, TException, TApplicationException
from ttypes import *

COMPRESSION_MAP = {
  "" :   0,
  "none" :   0,
  "deflate" :   1,
  "gzip" :   2,
  "bzip2" :   4,
  "snappy" :   5,
}
